### ISSUE TITLE
About the size mismatch

### ISSUE THREAD

**Issue by soberguo** [zengqunzhao/Exp-CLIP#1]
Thank you very much for your excellent work. While reproducing your results, I encountered a size mismatch problem despite using the same settings as your defaults. I look forward to your assistance. Thank you again.
`Traceback (most recent call last):
  File "/sharefiles/guoyixin/projects/Exp-CLIP-main/train.py", line 300, in <module>
    main()
  File "/sharefiles/guoyixin/projects/Exp-CLIP-main/train.py", line 70, in main
    model = ExpCLIP_Train(args)
  File "/sharefiles/guoyixin/projects/Exp-CLIP-main/models/Exp_CLIP.py", line 28, in __init__
    self.blip2 = get_blip2t5_model(device)
  File "/sharefiles/guoyixin/projects/Exp-CLIP-main/models/BLIP2_T5.py", line 372, in get_blip2t5_model
    model, _, _ = load_model_and_preprocess(
  File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/lavis/models/__init__.py", line 195, in load_model_and_preprocess
    model = model_cls.from_pretrained(model_type=model_type)
  File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/lavis/models/base_model.py", line 70, in from_pretrained
    model = cls.from_config(model_cfg)
  File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/lavis/models/blip2_models/blip2_t5.py", line 381, in from_config
    model.load_checkpoint_from_config(cfg)
  File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/lavis/models/base_model.py", line 100, in load_checkpoint_from_config
    self.load_from_pretrained(url_or_filename=pretrain_path, **kwargs)
  File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/lavis/models/blip2_models/blip2.py", line 93, in load_from_pretrained
    msg = self.load_state_dict(state_dict, strict=False)
  File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Blip2T5:
        size mismatch for t5_proj.weight: copying a param with shape torch.Size([4096, 768]) from checkpoint, the shape in current model is torch.Size([512, 768]).
        size mismatch for t5_proj.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([512]).`

**Comment by zengqunzhao** [comment]
> Thank you very much for your excellent work. While reproducing your results, I encountered a size mismatch problem despite using the same settings as your defaults. I look forward to your assistance. Thank you again. `Traceback (most recent call last): File "/sharefiles/guoyixin/projects/Exp-CLIP-main/train.py", line 300, in <module> main() File "/sharefiles/guoyixin/projects/Exp-CLIP-main/train.py", line 70, in main model = ExpCLIP_Train(args) File "/sharefiles/guoyixin/projects/Exp-CLIP-main/models/Exp_CLIP.py", line 28, in __init__ self.blip2 = get_blip2t5_model(device) File "/sharefiles/guoyixin/projects/Exp-CLIP-main/models/BLIP2_T5.py", line 372, in get_blip2t5_model model, _, _ = load_model_and_preprocess( File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/lavis/models/__init__.py", line 195, in load_model_and_preprocess model = model_cls.from_pretrained(model_type=model_type) File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/lavis/models/base_model.py", line 70, in from_pretrained model = cls.from_config(model_cfg) File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/lavis/models/blip2_models/blip2_t5.py", line 381, in from_config model.load_checkpoint_from_config(cfg) File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/lavis/models/base_model.py", line 100, in load_checkpoint_from_config self.load_from_pretrained(url_or_filename=pretrain_path, **kwargs) File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/lavis/models/blip2_models/blip2.py", line 93, in load_from_pretrained msg = self.load_state_dict(state_dict, strict=False) File "/home/guoyixin/miniconda3/envs/expclip/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for Blip2T5: size mismatch for t5_proj.weight: copying a param with shape torch.Size([4096, 768]) from checkpoint, the shape in current model is torch.Size([512, 768]). size mismatch for t5_proj.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([512]).`

Hey, I just ran the code on my side, and nothing wrong with it.
From what you just sent, I feel the issue is from the loading of the pre-trained Q-Former model. So my suggestion is to clean the pretrain modes cache, recreate the env and see if it works.
Hope this helps!

**Comment by soberguo** [comment]
Thank you very much for your reply. I tried the training again according to your suggestion, but the problem still occurs. I suspect that there is a problem with the loading of my pre-trained model. Can you provide the link where you loaded the pre-trained model? (My pre-trained model is loaded from https://huggingface.co/Salesforce/blip2-flan-t5-xxl. In addition to this, I also loaded bert from https://huggingface.co/google-bert/bert-base-uncased) Thank you again for your reply.

**Comment by zengqunzhao** [comment]
> Thank you very much for your reply. I tried the training again according to your suggestion, but the problem still occurs. I suspect that there is a problem with the loading of my pre-trained model. Can you provide the link where you loaded the pre-trained model? (My pre-trained model is loaded from https://huggingface.co/Salesforce/blip2-flan-t5-xxl. In addition to this, I also loaded bert from https://huggingface.co/google-bert/bert-base-uncased) Thank you again for your reply.

I'm not sure where the pre-train models were downloaded from, I just checked the path of the downloaded models, and they are located in ".cache/huggingface/hub/models--bert-base-uncased" and ".cache/huggingface/hub/models--google--flan-t5-xxl".

**Comment by zengqunzhao** [comment]
> > Thank you very much for your reply. I tried the training again according to your suggestion, but the problem still occurs. I suspect that there is a problem with the loading of my pre-trained model. Can you provide the link where you loaded the pre-trained model? (My pre-trained model is loaded from https://huggingface.co/Salesforce/blip2-flan-t5-xxl. In addition to this, I also loaded bert from https://huggingface.co/google-bert/bert-base-uncased) Thank you again for your reply.
> 
> I'm not sure where the pre-train models were downloaded from, I just checked the path of the downloaded models, and they are located in ".cache/huggingface/hub/models--bert-base-uncased" and ".cache/huggingface/hub/models--google--flan-t5-xxl".

[acw717@frontend11 hub]$ du -sh models--bert-base-uncased/
421M    models--bert-base-uncased/
[acw717@frontend11 hub]$ du -sh models--google--flan-t5-xxl/
42G     models--google--flan-t5-xxl/
[acw717@frontend11 hub]$

**Comment by soberguo** [comment]
Thanks for your reply, I have found the cause of the problem
