### ISSUE TITLE
Great work! But how should I set up my dataset？

### ISSUE THREAD

**Issue by qyx123** [zengqunzhao/Exp-CLIP#3]
- I have obtained the DFEW license, and I would like to try testing with the DFEW dataset. I modified --train.py: train_data_file_path = '/home/cs11/dataset/DFEW/DFEW_Frame_Face/' - is this correct?

- Additionally, I executed another task from your work: I ran preprocessing.py in DFER-CLIP to generate the DFEW_set_1_test.txt file with path = '/home/cs11/dataset/DFEW/DFEW_Frame_Face/' and saved it in the annotation folder of Exp-CLIP. 

- Therefore, I didn't modify --test.py: DATASET_PATH_MAPPING. When running sh runner.sh, I specified job_id = ExpCLIP_B32, load_model = ExpCLIP_B32, and didn't change any other parameters. However, during the training phase, it showed "killed", and during the testing phase, it showed NotADirectoryError: [Errno 20] Not a directory: './annotation/DFEW_set_1_test.txt'

Have you encountered this issue before? How can I resolve this problem? Below is the error code：

sh runner.sh
Training date:  24-10-23 10:54
************************
workers = 8
epochs = 5
batch_size = 512
batch_size_test_image = 512
batch_size_test_video = 64
lr = 0.001
weight_decay = 0.0001
momentum = 0.9
print_freq = 10
milestones = [30]
seed = 1
job_id = ExpCLIP-B32
instruction = Please play the role of a facial action describer. Objectively describe the detailed facial actions of the person in the image.
load_model = CLIP_B32
************************
/home/cs11/anaconda3/envs/expclip2/lib/python3.10/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
**Killed**
************************
load_model = CLIP_B32
job_id = ExpCLIP_B32
************************
************************************************************************** Zero-shot Prompt Type:  Class Name
Traceback (most recent call last):
  File "/home/cs11/Exp-CLIP/test.py", line 180, in <module>
    zero_shot_test_FER(FER_prompt, type_)
  File "/home/cs11/Exp-CLIP/test.py", line 151, in zero_shot_test_FER
    uar, war = zero_shot_test(dataset_=dataset, mode_task="Static_FER", FER_prompt_=FER_prompt_, prompt_type=type_)
  File "/home/cs11/Exp-CLIP/test.py", line 67, in zero_shot_test
    test_data = datasets.ImageFolder(test_data_path,
  File "/home/cs11/anaconda3/envs/expclip2/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/home/cs11/anaconda3/envs/expclip2/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/cs11/anaconda3/envs/expclip2/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
  File "/home/cs11/anaconda3/envs/expclip2/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 40, in find_classes
    classes = sorted([entry.name](http://entry.name/) for entry in os.scandir(directory) if entry.is_dir())
**NotADirectoryError: [Errno 20] Not a directory: './annotation/DFEW_set_1_test.txt'**

**Comment by zengqunzhao** [comment]
Hi I didn't encounter the first error on my side, seems something wrong with downloading pre-train models from HuggingFace.
For, the second one, if you already generated the DFEW_set_1_test.txt, then try the absolute path
